repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
    files: \.(java|c|h|hpp|cpp)$
  - id: trailing-whitespace
    files: \.(java|c|h|hpp|cpp)$
  - id: no-commit-to-branch
    args: [--branch, main]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format
    files: \.(java|c|h|hpp|cpp)$
    types_or: [file]
    args: ['-fallback-style=none', '-style=file']
