package frc.robot.constants.enums;

public enum AutoCommand {
  AUTO_PREP_GROUND_INTAKE,
  AUTO_PREP_GROUND_INTAKE_CUBE,
  AUTO_PREP_GROUND_INTAKE_CONE,
  AUTO_GROUND_INTAKE,
  AUTO_GROUND_INTAKE_CUBE,
  AUTO_GROUND_INTAKE_CONE,
  AUTO_POST_GROUND_INTAKE,
  AUTO_PREP_SCORE,
  AUTO_PREP_SCORE_CONE_2,
  AUTO_PREP_SCORE_CONE_0,
  AUTO_PREP_SCORE_CUBE_2,
  AUTO_PREP_SCORE_CUBE_1,
  AUTO_PREP_SCORE_CUBE_0,
  AUTO_SCORE_CUBE_0,
  AUTO_SCORE_CUBE_1,
  AUTO_SCORE_CUBE_2,
  AUTO_SCORE_CONE_2,
  AUTO_POST_SCORE,
  FORCE_CUBE_SHOT,
  FORCE_CONE_SHOT,
  AUTO_POST_GROUND_INTAKE_CONE,
  AUTO_WIRE_SCORE,
  AUTO_WIRE_PREP_SCORE,
  AUTO_WIRE_POST_SCORE
}
